import requests

map_list = [
    "arena_badlands",
    "arena_byre",
    "arena_granary",
    "arena_lumberyard",
    "arena_lumberyard_event",
    "arena_nucleus",
    "arena_offblast_final",
    "arena_perks",
    "arena_ravine",
    "arena_sawmill",
    "arena_watchtower",
    "arena_well",
    "cp_5gorge",
    "cp_altitude",
    "cp_ambush_event",
    "cp_badlands",
    "cp_brew",
    "cp_burghausen",
    "cp_canaveral_5cp",
    "cp_carrier",
    "cp_cloak",
    "cp_coldfront",
    "cp_degrootkeep",
    "cp_degrootkeep_rats",
    "cp_dustbowl",
    "cp_egypt_final",
    "cp_fastlane",
    "cp_foundry",
    "cp_freight_final1",
    "cp_frostwatch",
    "cp_gorge",
    "cp_gorge_event",
    "cp_granary",
    "cp_gravelpit",
    "cp_gravelpit_snowy",
    "cp_gullywash_final1",
    "cp_hadal",
    "cp_hardwood_final",
    "cp_junction_final",
    "cp_lavapit_final",
    "cp_manor_event",
    "cp_mercenarypark",
    "cp_metalworks",
    "cp_mossrock",
    "cp_mountainlab",
    "cp_overgrown",
    "cp_powerhouse",
    "cp_process_final",
    "cp_reckoner",
    "cp_snakewater_final1",
    "cp_snowplow",
    "cp_spookeyridge",
    "cp_standin_final",
    "cp_steer",
    "cp_sulfur",
    "cp_sunshine",
    "cp_sunshine_event",
    "cp_vanguard",
    "cp_well",
    "cp_yukon_final",
    "ctf_2fort",
    "ctf_2fort_invasion",
    "ctf_applejack",
    "ctf_crasher",
    "ctf_doublecross",
    "ctf_doublecross_snowy",
    "ctf_foundry",
    "ctf_frosty",
    "ctf_gorge",
    "ctf_haarp",
    "ctf_hellfire",
    "ctf_helltrain_event",
    "ctf_landfall",
    "ctf_pelican_peak",
    "ctf_sawmill",
    "ctf_snowfall_final",
    "ctf_thundermountain",
    "ctf_turbine",
    "ctf_turbine_winter",
    "ctf_well",
    "itemtest",
    "koth_badlands",
    "koth_bagel_event",
    "koth_brazil",
    "koth_cachoeira",
    "koth_cascade",
    "koth_harvest_event",
    "koth_harvest_final",
    "koth_highpass",
    "koth_king",
    "koth_krampus",
    "koth_lakeside_event",
    "koth_lakeside_final",
    "koth_lazarus",
    "koth_los_muertos",
    "koth_maple_ridge_event",
    "koth_megalo",
    "koth_megaton",
    "koth_moonshine_event",
    "koth_nucleus",
    "koth_probed",
    "koth_rotunda",
    "koth_sawmill",
    "koth_sawmill_event",
    "koth_sharkbay",
    "koth_slasher",
    "koth_slaughter_event",
    "koth_slime",
    "koth_snowtower",
    "koth_sujin",
    "koth_synthetic_event",
    "koth_undergrove_event",
    "koth_viaduct",
    "koth_viaduct_event",
    "mvm_bigrock",
    "mvm_coaltown",
    "mvm_decoy",
    "mvm_ghost_town",
    "mvm_mannhattan",
    "mvm_mannworks",
    "mvm_rottenburg",
    "pass_brickyard",
    "pass_district",
    "pass_timbertown",
    "pd_atom_smash",
    "pd_cursed_cove_event",
    "pd_farmageddon",
    "pd_galleria",
    "pd_mannsylvania",
    "pd_monster_bash",
    "pd_pit_of_death_event",
    "pd_selbyen",
    "pd_snowville_event",
    "pd_watergate",
    "pd_badwater",
    "pd_barnblitz",
    "pd_bloodwater",
    "pd_borneo",
    "pl_breadspace",
    "pl_cactuscanyon",
    "pl_camber",
    "pl_cashworks",
    "pl_chilly",
    "pl_coal_event",
    "pl_corruption",
    "pl_embargo",
    "pl_emerge",
    "pl_enclosure_final",
    "pl_fifthcurve_event",
    "pl_frontier_final",
    "pl_frostcliff",
    "pl_goldrush",
    "pl_hasslecastle",
    "pl_hoodoo_final",
    "pl_millstone_event",
    "pl_odyssey",
    "pl_phoenix",
    "pl_pier",
    "pl_precipice_event_final",
    "pl_rumble_event",
    "pl_rumford_event",
    "pl_sludgepit_event",
    "pl_snowycoast",
    "pl_spineyard",
    "pl_swiftwater_final1",
    "pl_terror_event",
    "pl_thundermountain",
    "pl_upward",
    "pl_venice",
    "pl_wutville_event",
    "plr_bananabay",
    "plr_hacksaw",
    "plr_hacksaw_event",
    "plr_hightower",
    "plr_hightower_event",
    "plr_nightfall_final",
    "plr_pipeline",
    "rd_asteroid",
    "sd_doomsday",
    "sd_doomsday_event",
    "tc_hydro",
    "tr_dustbowl",
    "tr_target",
    "vsh_distillery",
    "vsh_nucleus",
    "vsh_skirmish",
    "vsh_tinyrock",
    "zi_atoll",
    "zi_devestation_final1",
    "zi_murky",
    "zi_sanitarium",
    "zi_woods"
]

resources = "https://resources.redchanit.xyz/"
maps = resources+"maps/tf2/"
counter = 0

def is_downloadable(url):
    h = requests.head(url, allow_redirects=True)
    header = h.headers
    content_type = header.get('content-type')
    if 'text' in content_type.lower():
        return False
    if 'html' in content_type.lower():
        return False
    return True

map_list.insert(0, "")
for element in map_list:
    counter += 1
    try:
     filename = map_list[counter]+".png"
     if is_downloadable(maps+filename):
         print("downloading "+ maps+filename)
         r = requests.get(maps+filename, allow_redirects=True)
         open(map_list[counter]+".png", 'wb').write(r.content)
         print("counter: "+str(counter)+"/"+str(len(map_list)))
     else:
         print("skipping "+maps+filename)
         print("counter: "+str(counter)+"/"+str(len(map_list)))
    except IndexError:
        print("done!")
        break
    
    
    